# Do not forget to change status badge in ./README.md
name: frontend_on_push_branch_execute_ci_cd

on:
  push:
    branches: [main]
  # See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
  pull_request:
    # Only branches and tags on the base are evaluated
    branches: [main]

env:
  NODE_VERSION: "18.12.1"

jobs:
  build_deps:
    runs-on: ubuntu-latest
    container: node:18.20-bookworm-slim

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache-npm
        with:
          path: npm-cache
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-v3

      - run: npm --prefix frontend --cache npm-cache ci

  frontend_check_npm_lint:
    runs-on: ubuntu-latest
    container: node:18.20-bookworm-slim

    needs: build_deps

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache-npm
        with:
          path: npm-cache
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-v3

      - run: npm --prefix frontend --cache npm-cache ci     
      - run: npm --prefix frontend run lint

  frontend_check_npm_check_types:
    runs-on: ubuntu-latest
    container: node:18.20-bookworm-slim

    needs: build_deps

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache-npm
        with:
          path: npm-cache
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-v3

      - run: npm --prefix frontend --cache npm-cache ci   
      - run: npm --prefix frontend run check-types


  frontend_check_npm_test:
    runs-on: ubuntu-latest
    container: node:18.20-bookworm-slim

    needs: build_deps

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache-npm
        with:
          path: npm-cache
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-v3

      - run: npm --prefix frontend --cache npm-cache ci   
      - run: npm --prefix frontend run test